name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: macos-latest
            architecture: arm64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      if: ${{ matrix.os }} != 'macos-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.0.x

    - name: Install .NET SDK
      if: ${{ matrix.os }} == 'macos-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Build and test
      run: dotnet test
