name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build and test
      run: dotnet test
