name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build and test on ${{ matrix.os }} ${{ matrix.architecture }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            architecture: x64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      if: matrix.os != 'macos-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install .NET SDK
      if: matrix.os == 'macos-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Build and test
      run: dotnet test
