name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build and test on ${{ matrix.os }} ${{ matrix.architecture }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            architecture: x64
          - os: windows-latest
            architecture: x64
          - os: macos-latest
            architecture: arm64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      if: matrix.os == 'macos-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Install libssl
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt -y install libssl3

    - name: Build and test
      run: dotnet test
