name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build and test on ${{ matrix.os }} ${{ matrix.architecture }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            architecture: x64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          2.x
          8.x

    - name: Install libssl
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

    - name: Install libssl
      if: matrix.os == 'ubuntu-24.04-arm'
      run: |
        wget http://ports.ubuntu.com/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_arm64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_arm64.deb

  test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Test
      run: dotnet test
