name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        default: "1.0.0"

jobs:

  build-and-test:
  
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set the release version
      run: echo ${{ github.event.inputs.release-version }}"

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build
