name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        default: "1.0.0"

jobs:
  release:
    name: Release v${{github.event.inputs.release-version}}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check the package release version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ["${{github.event.inputs.release-version}}" = "1.0.0"] && gh run cancel ${{github.run_id}} && gh run watch ${{github.run_id}}
        exit 0

    - name: Set the package release version
      uses: richardrigutins/replace-in-files@v2
      with:
        files: 'dotMap/dotMap.csproj'
        search-text: '<Version>.*</Version>'
        replacement-text: '<Version>${{github.event.inputs.release-version}}</Version>'

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Set the new job version
      uses: richardrigutins/replace-in-files@v2
      with:
        files: '.github/workflows/release.yml'
        search-text: 'default: ".*"'
        replacement-text: 'default: "{{github.event.inputs.release-version}}"'
