name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        default: "1.0.0"

jobs:
  release:
    name: Release v${{github.event.inputs.release-version}}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check the package release version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        [ "${{github.event.inputs.release-version}}" = "1.0.0" ] && gh run cancel ${{github.run_id}} && gh run watch ${{github.run_id}}
        exit 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          2.x
          8.x

    - name: Install libssl
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

    - name: Set the package release version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "<Version>.*</Version>"
        replace: "<Version>${{github.event.inputs.release-version}}</Version>"
        include: "dotMap/dotMap.csproj"
        regex: true

    - name: Set 
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "name: Continuous Integration"
        replace: "name: Continuous Integration2"
        include: ".github/workflows/ci.yml"
        regex: false

    - name: Build
      run: dotnet build -c Release

    - name: Commit the new version
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dotMap/dotMap.csproj
        git commit -m "Release v${{github.event.inputs.release-version}}"
        
    - name: Push and save the new version
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
